# ansible-playbook -i hosts fedora.yml -K
---
- name: Configure Fedora WorkStation settings
  hosts: all
  gather_facts: false

  become: true
  become_user: root

  tasks:

  - include_role:
      name: wifi
    vars:
      wifi_default_randomize: true
      wifi_network_no_randomize: "Dragonite"

  - include_role:
      name: baseline
    vars:
      baseline_packages:
        - vim
        - ansible
        - libselinux-python
